### ISSUE TITLE
Solr field candidates to go away

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#1047]
Based on looking through indexing code.  Before removing any:
- do a global search in dor_indexing_app for the exact field name, and possibly for the string before the fieldtype prefix
- ditto for argo
- for sul_dlss github organization repos
- hydra_etd and google-books (private repos)

Candidates:
- [x] **sw_author_tesim** - ~~cleanup after fixing author search (sul-dlss/argo/issues/4231)~~ used for display in Argo
    - [x] new field author_display_ss sul-dlss/dor_indexing/pull/21 - populating as of 2/16/24
    - [x] new field populated 2/21/24
    - [x] replaced in consuming code (argo only) sul-dlss/argo/pull/4324
    - [x] old field no longer indexed after argo deployed to prod https://github.com/sul-dlss/dor_indexing/pull/33
- [x] **objectId_tesim** - um ... can't we use id or some other indexing of bare_druid and prefixed_druid ?
    - [x] new fields - sul-dlss/dor_indexing/pull/17 - populating as of 2/16/24
    - [x] new field populated 2/21/24
    - [x] replaced in consuming code (see sul-dlss/dor_indexing_app/issues/1031)
    - [x] old field no longer indexed after consuming code deployed to prod sul-dlss/dor_indexing/pull/34
- [ ] **object_label_tesim** ? See sul-dlss/argo/issues/4262
- [x] **source_id_ssim** - cleanup after PRs #1038,  sul-dlss/argo/pull/4256 and sul-dlss/argo/issues/4194 and #1084
- [x] **exploded_tag_ssim** - cleanup after sul-dlss/argo/pull/4206, sul-dlss/argo/issues/4187
- [x] **metadata_format_ssim** - not used sul-dlss/dor_indexing/pull/20/
- [x] **metadata_source_ssi** vs **metadata_source_ssim** --see #946 and #947 (done?)
- [x] solr_doc["#{prefix}_tag_ssim"] in admintags line 33 ... is this to make the tag searchable?  sul_tag_ssim?? -- address with code refactor and better comments
- [x] various identifier flavors;  besides bare and prefixed for each of druid, barcode, sourceid, folio instance id, previous ils ids, doi ... what else?  do we need all these?
    - see objectId_tesim above

**Comment by ndushay** [comment]
For each field to be deleted:
- [ ] search argo for any usage
- [ ] search dor_indexing_app for any usage
- [ ] search rest of infra apps for any usage (?)
- [ ] search dor_services_app for any usage
- [ ] ensure we no longer index to it in dor_indexing_app
- [ ] watch it being depopulated in solr admin schema interface
     
<img width="709" alt="image" src="https://github.com/sul-dlss/dor_indexing_app/assets/96775/bad61d5b-87a0-441c-ac98-7c6808900aa1">

**Comment by ndushay** [comment]
closing this;  all is done except remaining uses of obj_label and that is ticketed as sul-dlss/argo#4262
