### ISSUE TITLE
title searching: improve recall and precision

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#1075]
For title searches, we want these flavors:
- anchored for exactish (boosted highest)
- text without stemming (boosted next highest)
- text stemmed (English) (boosted lowest of these three)

# TODO:
- [x] argo's local dev solr schema.xml updated for these field types: https://github.com/sul-dlss/argo/pull/4259 and deployed
- [x] sul-solr config files updated for tokenized unstemmed field, and for experimental searcher: sul-dlss/sul-solr-configs/pull/280 and sul-dlss/sul-solr-configs/pull/281 deploy
    - [x] argo_qa solr
    - [x] argo_stage solr
    - [x] argo_prod solr
- [x] cocina-models has logic to extract main title, full title and additional titles (v 0.93.1)
- [x] cocina-models revised to leave .build as it was sul-dlss/cocina-models/pull/672
- [x] remove trailing whitespace when appropriate sul-dlss/cocina-models/pull/674
- [ ] ~~cocina-models revised to include more pieces in uniform titles when available~~
- [x] cocina-models specs get detailed title specs from dor_indexing gem sul-dlss/cocina-models/pull/676
- [x] cocina-models v 0.94.2 released with changes above
- [x] dor_indexing gem uses new cocina-models sul-dlss/dor_indexing/pull/11
- [x] dor_indexing gem populates new title fields and removes detailed title specs now in cocina-models gem https://github.com/sul-dlss/dor_indexing/pull/12
- [x] release new dor_indexing gem  v1.2.0
- [x] dor_indexing_app populates (new title fields)
   - [x] dor_indexing_app PR for updated dor_indexing gem sul-dlss/dor_indexing_app/pull/1095
   - [x] deployed to qa 
   - [x] deployed to stage 
   - [x] deployed to prod w dep updates 1/29/24
- [x] dsa rolling indexer makes new title fields
   - [x] dsa PR for updated dor_indexing gem sul-dlss/dor-services-app/pull/4684
   - [x] deployed to qa
   - [x] deployed to stage
   - [x] deployed to prod w dep updates 1/29/24
- [x] sul-solr-config has copyField definitions sul-dlss/sul-solr-configs/pull/295
- [x] argo solr prod (new title) fields have begun populating (with dep updates on Mon 1/29/24)
- [x] argo solr prod fields have finished populating - http://sul-solr-prod-a.stanford.edu/solr/argo_prod/select?q=main_title_tenim:*&fl=id&facet=false&rows=0 (as of 2/5/24)
- update Argo solr and/or app (add it to blacklight_config_helper) to use new field(s) for searching by default (and add weighting and to pf, etc.)
   - [x] solr config changes deployed to qa sul-dlss/sul-solr-configs/pull/309
   - [x] solr config changes deployed to stage sul-dlss/sul-solr-configs/pull/309
   - [x] solr config changes deployed to prod 
   - [x] argo changes deployed to qa (will happen with dep updates week of 3/11)
   - [x] argo changes deployed to stage
   - [x] argo changes deployed to prod (will happen with dep updates week of 3/11)
- [x] argo repo solr config changes sul-dlss/argo/pull/4317
- [x] dor-services-app repo solr config changes sul-dlss/dor-services-app/pull/4692
- [x] stop indexing to sw_display_title_tesim title fields (dor_indexing gem)
- [x] remove old title fields
    - [x] argo sul-dlss/argo/pull/4317, 
    - [x] dor_indexing gem sul-dlss/dor_indexing/pull/39
    - [x] dor-indexing-app
    - [x] dor-services-app
    - [x] solrconfigs

**Comment by ndushay** [comment]
I hearby declare this ticket done.
