### ISSUE TITLE
EPIC: Add Facet Field for Released to Searchworks 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#846]
I would hope this could be a date field and we would want the ability to explicitly display "none" or whatever.

There are at least these pieces to this:
- [x] add field to Solr index for argo (or use dynamic naming for field)
- [x] add code to appropriately index the data
- [x] have a plan to get all the data indexed (could be just waiting for rolling reindexing to run through all the records)
- [x] configure argo to show the new facet, as Andrew desires (which views, where in the list of facets)
- [ ] remove "released to" field after new fields are populated "enough"

**Comment by ndushay** [comment]
I would assume we can determine the release date from a timestamp for the ? update-marc workflow step in the  (first?) releaseWF, or something like that, for objects as they are, and for newly accessioning objects, we can add this step or add code for this to the releaseWF?

Questions for @andrewjbtw :
- What should the UI be?  Something like the Last Published facet providing some built in facet values, and a way to use a date range?  (which built in facet values?)
- do you want the facet values to be the actual date (day only, or with timestamp)?

For reference, it looks like the code doing the release to searchworks is https://github.com/sul-dlss/dor-services-app/blob/main/app/services/update_marc_record_service.rb;  how we go about getting the correct info indexed is part of this ticket.

**Comment by andrewjbtw** [comment]
It might be that we have to separate EarthWorks and SearchWorks. I could see facet values like:

- Last 7 days
- Last month
- Last year
- Ever (maybe needs a better name but meaning "currently released" regardless of when)
- Not released

That gets complicated when you need to specify "released to SW" or "released to EW" unless we separate the two.

**Comment by jcoyne** [comment]
<img width="472" alt="Screen Shot 2022-05-31 at 3 48 28 PM" src="https://user-images.githubusercontent.com/92044/171281927-216622fe-5939-4aa1-86d9-b9c8bfadcce8.png">
@ndushay is there a reason you don't want to use the date in the release tags and are looking for the workflow instead?

**Comment by ndushay** [comment]
@jcoyne I wasn't sure where to look for the date -- the release tags are superior to my idea - thanks.

The actions for this ticket are:

- [ ] add fields to Solr index for argo (or use dynamic naming for field)
- [ ] add code to appropriately index the data as dates (I suspect day granularity is fine - check with Andrew)
- [ ] have a plan to get all the data indexed (could be just waiting for rolling reindexing to run through all the records)
- [ ] configure argo to show the new facets, as Andrew desires (which views, where in the list of facets) - and explicitly indicate missing as "Not released" per his comment
- [ ] remove the old facet once the new one is populated and showing in argo.

This can be split into separate tickets.

**Comment by ndushay** [comment]
In Solr parlance, we have to set `facet.missing=true` for the new fields.
