### ISSUE TITLE
Index argo facets starting "SW" with the same code used by SearchWorks for those facets

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#992]
Use stanford_mods code to index the Argo facets that are supposed to be akin to SearchWorks facets.  There is an exemplar PR #993.  I think a single PR for all the rest of the facets below is fine, but that's up to you.

The below is condensed from https://docs.google.com/spreadsheets/d/1s4gQcPEY_YPGrDOFXQQ1IbRYBc3AaKGRIPW1FFw46G0/, where I traced Argo and SearchWorks for catalog config information for Solr facet field names and then chased indexing code in searchworks_traject_indexer to get to the methods used to populate the SearchWorks facet fields.  See also the epic sul-dlss/argo#3168 for more info.

All SW facets:
-  UI facet name | Argo Solr field | SW Solr field | stanford_mods method
- [ ] SW Resource type | sw_format_ssim | format_main_ssim | Stanford::Mods::Searchworks.format_main (PR #1005)
- [x] SW Date | sw_pub_date_facet_ssi | pub_year_tisim | Stanford::Mods::OriginInfo.pub_year_int (See PR #1008)
- [x] SW Topic | topic_ssim | topic_facet | Stanford::Mods::SearchworksSubjects.topic_facet (See PR #1009)
- [ ] SW Region | sw_subject_geographic_ssim | geographic_facet | Stanford::Mods::SearchworksSubjects.geographic_facet (PR #1010)
- [x] SW Era | sw_subject_temporal_ssim | era_facet | Stanford::Mods::SearchworksSubjects.era_facet (See PR #1011)
- [x] SW Genre | sw_genre_ssim | genre_ssim | Stanford::Mods::Searchworks.sw_genre (See PR #993)
- [x] SW Language | sw_language_ssim | language : sw_language_facet | Stanford::Mods::Searchworks.sw_language_facet (PR #1012)

**Comment by ndushay** [comment]
The below is condensed from https://docs.google.com/spreadsheets/d/1s4gQcPEY_YPGrDOFXQQ1IbRYBc3AaKGRIPW1FFw46G0/, where I traced Argo and SearchWorks for catalog config information for Solr facet field names and then chased indexing code in searchworks_traject_indexer to get to the methods used to populate the SearchWorks facet fields.

All SW facets:
-  UI facet name : Argo Solr field : SW Solr field : stanford_mods method
- [ ] SW Resource type : sw_format_ssim : format_main_ssim : Stanford::Mods::Searchworks.format_main
- [ ] SW Date : sw_pub_date_facet_ssi : pub_year_tisim : Stanford::Mods::OriginInfo.pub_year_int
- [ ] SW Topic : topic_ssim : topic_facet : Stanford::Mods::SearchworksSubjects.topic_facet
- [ ] SW Region : sw_subject_geographic_ssim : geographic_facet :  Stanford::Mods::SearchworksSubjects.geographic_facet
- [ ] SW Era : sw_subject_temporal_ssim : era_facet : Stanford::Mods::SearchworksSubjects.era_facet
- [x] SW Genre : sw_genre_ssim : genre_ssim : Stanford::Mods::Searchworks.sw_genre
- [ ] SW Language : sw_language_ssim : language : sw_language_facet : Stanford::Mods::Searchworks.sw_language_facet

**Comment by ndushay** [comment]
ACTION ITEM per discussion with @andrewjbtw @ndushay and @aaron-collier on 10/3/23:  Aaron will write "report" tickets for sussing out the differences between stanford mods indexing and dor-indexing-app for this part of descriptive metadata.

**Comment by ndushay** [comment]
closing this ticket;  there are some tendrils in PRs #1005 and #1010 and we will follow through for those tickets.
